[build]
command = "npm run build"
publish = "dist"

[environment]
NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[redirects]]
from = "http://*"
to = "https://:splat"
status = 301
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' https: data:; font-src 'self' https: data:; connect-src 'self' https:;"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"